//AS3 exporter version 2.2, generated by Away3D: http://www.away3d.com
package katok
{
	import away3d.containers.ObjectContainer3D;
	import away3d.containers.Scene3D;
	import away3d.core.math.*;
	import away3d.materials.*;
	import away3d.core.base.*;
	import away3d.core.utils.Init;
	import away3d.loaders.utils.*;
	import away3d.loaders.data.*;
	import flash.utils.Dictionary;
	import away3d.primitives.*;

	public class KatokMesh extends ObjectContainer3D
	{
		private var objs:Object = {};
		private var geos:Array = [];
		private var oList:Array =[];
		private var aC:Array;
		private var aV:Array;
		private var aU:Array;
		private var _scale:Number;

		public function KatokMesh(init:Object = null)
		{
			var ini:Init = Init.parse(init);
			_scale = ini.getNumber("scaling", 1);
			setSource();
			addContainers();
			buildMeshes();
			buildMaterials();
			cleanUp();
		}

		private function buildMeshes():void
		{			var m0:MatrixAway3D = new MatrixAway3D();
			m0.sxx = 1;
			m0.sxy = 0;
			m0.sxz = 0;
			m0.tx = -0.0378568172454834*_scale;
			m0.syx = 0;
			m0.syy = 1;
			m0.syz = 0;
			m0.ty = -1.7310083508491516*_scale;
			m0.szx = 0;
			m0.szy = 0;
			m0.szz = 1;
			m0.tz = 60.56991767883301*_scale;

			objs.obj0 = {name:"St_b_left",  transform:m0, pivotPoint:new Number3D(-0.0378568172454834,-1.7310083508491516,60.56991767883301), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj0.geo=geos[0];
			var m1:MatrixAway3D = new MatrixAway3D();
			m1.sxx = 1;
			m1.sxy = 0;
			m1.sxz = 0;
			m1.tx = 29.90640926361084*_scale;
			m1.syx = 0;
			m1.syy = 1;
			m1.syz = 0;
			m1.ty = -1.7368143051862717*_scale;
			m1.szx = 0;
			m1.szy = 0;
			m1.szz = 1;
			m1.tz = 0.5505827963352203*_scale;

			objs.obj1 = {name:"St_t_right",  transform:m1, pivotPoint:new Number3D(29.90640926361084,-1.7368143051862717,0.5505827963352203), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj1.geo=geos[1];
			var m2:MatrixAway3D = new MatrixAway3D();
			m2.sxx = 1;
			m2.sxy = 0;
			m2.sxz = 0;
			m2.tx = 0.19838333129882813*_scale;
			m2.syx = 0;
			m2.syy = 1;
			m2.syz = 0;
			m2.ty = -1.7473875284194946*_scale;
			m2.szx = 0;
			m2.szy = 0;
			m2.szz = 1;
			m2.tz = 1.0158399939537048*_scale;

			objs.obj2 = {name:"St_t_left",  transform:m2, pivotPoint:new Number3D(0.19838333129882813,-1.7473875284194946,1.0158399939537048), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj2.geo=geos[2];
			var m3:MatrixAway3D = new MatrixAway3D();
			m3.sxx = 1;
			m3.sxy = 0;
			m3.sxz = 0;
			m3.tx = -0.3426567614078522*_scale;
			m3.syx = 0;
			m3.syy = 1;
			m3.syz = 0;
			m3.ty = -0.5200989246368408*_scale;
			m3.szx = 0;
			m3.szy = 0;
			m3.szz = 1;
			m3.tz = 30.98613154888153*_scale;

			objs.obj3 = {name:"bort_right",  transform:m3, pivotPoint:new Number3D(-0.3426567614078522,-0.5200989246368408,30.98613154888153), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj3.geo=geos[3];
			var m4:MatrixAway3D = new MatrixAway3D();
			m4.sxx = 1;
			m4.sxy = 0;
			m4.sxz = 0;
			m4.tx = 15.235110104084015*_scale;
			m4.syx = 0;
			m4.syy = 1;
			m4.syz = 0;
			m4.ty = -0.515721321105957*_scale;
			m4.szx = 0;
			m4.szy = 0;
			m4.szz = 1;
			m4.tz = 59.89401435852051*_scale;

			objs.obj4 = {name:"bort_bottom",  transform:m4, pivotPoint:new Number3D(15.235110104084015,-0.515721321105957,59.89401435852051), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj4.geo=geos[4];
			var m5:MatrixAway3D = new MatrixAway3D();
			m5.sxx = 1;
			m5.sxy = 0;
			m5.sxz = 0;
			m5.tx = 30.918472290039063*_scale;
			m5.syx = 0;
			m5.syy = 1;
			m5.syz = 0;
			m5.ty = -0.5308123826980591*_scale;
			m5.szx = 0;
			m5.szy = 0;
			m5.szz = 1;
			m5.tz = 31.26710867881775*_scale;

			objs.obj5 = {name:"bort_left",  transform:m5, pivotPoint:new Number3D(30.918472290039063,-0.5308123826980591,31.26710867881775), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj5.geo=geos[5];
			var m6:MatrixAway3D = new MatrixAway3D();
			m6.sxx = 1;
			m6.sxy = 0;
			m6.sxz = 0;
			m6.tx = 15.285278260707855*_scale;
			m6.syx = 0;
			m6.syy = 1;
			m6.syz = 0;
			m6.ty = -0.515721321105957*_scale;
			m6.szx = 0;
			m6.szy = 0;
			m6.szz = 1;
			m6.tz = 2.313973218202591*_scale;

			objs.obj6 = {name:"bort_top",  transform:m6, pivotPoint:new Number3D(15.285278260707855,-0.515721321105957,2.313973218202591), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj6.geo=geos[6];
			var m7:MatrixAway3D = new MatrixAway3D();
			m7.sxx = 1;
			m7.sxy = 0;
			m7.sxz = 0;
			m7.tx = 30.147090911865234*_scale;
			m7.syx = 0;
			m7.syy = 1;
			m7.syz = 0;
			m7.ty = -1.7361227869987488*_scale;
			m7.szx = 0;
			m7.szy = 0;
			m7.szz = 1;
			m7.tz = 60.38124084472656*_scale;

			objs.obj7 = {name:"St_b_right",  transform:m7, pivotPoint:new Number3D(30.147090911865234,-1.7361227869987488,60.38124084472656), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj7.geo=geos[7];
			var m8:MatrixAway3D = new MatrixAway3D();
			m8.sxx = 1;
			m8.sxy = 0;
			m8.sxz = 0;
			m8.tx = 14.969133843667805*_scale;
			m8.syx = 0;
			m8.syy = 1;
			m8.syz = 0;
			m8.ty = -2.2972689270973206*_scale;
			m8.szx = 0;
			m8.szy = 0;
			m8.szz = 1;
			m8.tz = 30.64709883928299*_scale;

			objs.obj8 = {name:"Ice",  transform:m8, pivotPoint:new Number3D(14.969133843667805,-2.2972689270973206,30.64709883928299), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj8.geo=geos[8];

			var ref:Object;
			var mesh:Mesh;
			var j:int;
			var av:Array;
			var au:Array;
			var v0:Vertex;
			var v1:Vertex;
			var v2:Vertex;
			var u0:UV;
			var u1:UV;
			var u2:UV;
			var aRef:Array ;
			for(var i:int = 0;i<9;++i){
				ref = objs["obj"+i];
				if(ref != null){
					mesh = new Mesh();
					mesh.type = ".as";
					mesh.bothsides = ref.bothsides;
					mesh.name = ref.name;
					mesh.pushfront = ref.pushfront;
					mesh.pushback = ref.pushback;
					mesh.ownCanvas = ref.ownCanvas;
					if(aC[ref.container]!= null)
						aC[ref.container].addChild(mesh);

					oList.push(mesh);
					mesh.transform = ref.transform;
					mesh.movePivot(ref.pivotPoint.x, ref.pivotPoint.y, ref.pivotPoint.z);
					if (ref.geo.geometry != null) {
						mesh.geometry = ref.geo.geometry;
						continue;
					}
					ref.geo.geometry = new Geometry();
					mesh.geometry = ref.geo.geometry;
					aRef = ref.geo.f.split(",");
					for(j = 0;j<aRef.length;j+=6){
						try{
							av = ref.geo.aV[parseInt(aRef[j], 16)].split("/");
							v0 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							av = ref.geo.aV[parseInt(aRef[j+1],16)].split("/");
							v1 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							av = ref.geo.aV[parseInt(aRef[j+2],16)].split("/");
							v2 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							au = ref.geo.aU[parseInt(aRef[j+3],16)].split("/");
							u0 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							au = ref.geo.aU[parseInt(aRef[j+4],16)].split("/");
							u1 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							au = ref.geo.aU[parseInt(aRef[j+5],16)].split("/");
							u2 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							ref.geo.geometry.addFace( new Face(v0, v1, v2, ref.material, u0, u1, u2) );
						}catch(e:Error){
							trace("obj"+i+": ["+aV[parseInt(aRef[j],16)].split("/")+"],["+aV[parseInt(aRef[j+1],16)].split("/")+"],["+aV[parseInt(aRef[j+2],16)].split("/")+"]");
							trace("     uvs: ["+aV[parseInt(aRef[j+3],16)].split("/")+"],["+aV[parseInt(aRef[j+4],16)].split("/")+"],["+aU[parseInt(aRef[j+5],16)].split("/")+"]");
						}
					}
				}
			}
		}

		private function setSource():void
		{
			var geo0:Object = {};
			geo0.aVstr="0.1bbd/-0.fe4/3d.de1,-0.1995/-0.fe4/3b.1a7c,-0.61a/-0.fe4/3b.aa2,1.827/-0.fe4/3c.2517,0.0324/-3.0228/3d.21e4,-1.b1d/-3.0228/3c.76f,1.827/-3.0228/3c.2517,-0.61a/-3.0228/3b.aa2";
			geo0.aUstr="0.1e5bfef5c1acdb/0.1938cb502df807,0.1cf9e255efce9c/0.1938cb502df807,0.1cf9e255efce9c/0.16828802e4c7b9,0.1e5bfef5c1acdb/0.16828802e4c7b9,0.1ce2620980b1c9/0.17265e04484431,0.1ce2620980b1c9/0.152b4506b778cd,0.1e572cf274cb27/0.152b4506b778cd,0.1e572cf274cb27/0.17265e04484431,0.163863a3730f33/0,0.1812d1752bb976/0,0.1812d1752bb976/1,0.163863a3730f33/1,0.1d006a0dd39528/0.12a1a2c07e76fb,0.1de21f9c7fe268/0.12a1a2c07e76fb,0.1de21f9c7fe268/0.13835aab20dda7,0.1d006a0dd39528/0.13835aab20dda7,0.303d25d2af90c/0.147a45e9073c7b,0.1cc61906162681/0.147a45e9073c7b,0.1cc61906162681/0.1e903adfea944,0.303d25d2af90c/0.1e903adfea944";
			geo0.aV= read(geo0.aVstr).split(",");
			geo0.aU= read(geo0.aUstr).split(",");
			geo0.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,6,7,5,8,9,a,6,5,4,8,a,b,2,1,5,c,d,e,2,5,7,c,e,f,3,6,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo0);
			var geo1:Object = {};
			geo1.aVstr="1d.039a/-0.114a/-0.67b,1e.176c/-0.114a/1.f07,1e.569/-0.114a/1.2088,1c.18a8/-0.114a/0.b07,1d.1a57/-3.0136/-0.1c95,1f.718/-3.0136/0.1ffd,1c.18a8/-3.0136/0.b07,1e.569/-3.0136/1.2088";
			geo1.aUstr="0.1e25925adbd48d/0.1d58b9f119665d,0.1d05ca2cea35e0/0.1d58b9f119665d,0.1d05ca2cea35e0/0.1c38ef6731ae44,0.1e25925adbd48d/0.1c38ef6731ae44,0.302cb086d01b7/0.16d570d6b89e63,0.302cb086d01b7/0.183aa7694a6012,0.1d155536fb1a50/0.183aa7694a6012,0.1d155536fb1a50/0.16d570d6b89e63,0/0,1/0,1/1,0/1,0.1e2de973dbb2b3/0.1da37ca901aafb,0.1d05a99009a949/0.1da37ca901aafb,0.1d05a99009a949/0.1c7b3cc52fa191,0.1e2de973dbb2b3/0.1c7b3cc52fa191,0.3060e32bc28ce/0.1b428fe91ef508,0.1cd17c0d984200/0.1b428fe91ef508,0.1cd17c0d984200/0.19d77dd7d6ac8d,0.3060e32bc28ce/0.19d77dd7d6ac8d";
			geo1.aV= read(geo1.aVstr).split(",");
			geo1.aU= read(geo1.aUstr).split(",");
			geo1.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,6,7,5,8,9,a,6,5,4,8,a,b,2,1,5,c,d,e,2,5,7,c,e,f,3,6,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo1);
			var geo2:Object = {};
			geo2.aVstr="-0.d07/-0.119c/1.258a,0.2201/-0.119c/0.66f,1.fcd/-0.119c/0.146a,0.7d6/-0.119c/2.c75,-1.004e/-3.01b8/1.13e3,0.7aa/-3.01b8/-0.b39,1.fcd/-3.01b8/0.146a,0.7d6/-3.01b8/2.c75";
			geo2.aUstr="0.30ab43461577b/0.0020a72a6c560d38,0.30ab43461577b/0.2384efd9217550,0.1cf289101208e4/0.38d4b6bb58e46,0.1cf28b6c082250/0.00184b1febd6b34e,0.1ce8c2342891eb/0.eefc9e2c4defe,0.1ce8c2342891eb/0.82abc27bb1f770,0.1e489b0399cc4d/0.82abc27bb1f770,0.1e489b0399cc4d/0.eefc9e2c4defe,0.1648ec80a60c11/0,0.197a24275b4626/0,0.197a24275b4626/1,0.1648ec80a60c11/1,0.1df1aaca17b948/0.f93b7467aee05,0.1d7266bd5a0db6/0.f8e265f9a6cdc,0.1ce02c3d5db404/0.89add466b77758,0.1e0020d3fe5e63/0.dd12df3c91fc4,0.1dfd37bacbd49c/0.660269d25ccba4,0.1cd04d60e8cfe9/0.660269d25ccba4,0.1cd04d60e8cfe9/0.90688ebbf4977,0.1dfd37bacbd49c/0.90688ebbf4977";
			geo2.aV= read(geo2.aVstr).split(",");
			geo2.aU= read(geo2.aUstr).split(",");
			geo2.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,3,2,6,8,9,a,3,6,7,8,a,b,2,1,5,c,d,e,2,5,6,c,e,f,3,7,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo2);
			var geo3:Object = {};
			geo3.aVstr="0.1e56/1.2007/3a.013e,0.1505/-2.22b0/39.1701,-1.120b/-2.22b0/39.1701,-1.8ba/1.2007/3a.013e,0.1e56/1.211e/4.013e,-1.8ba/1.20fd/4.013e,-1.120b/-2.22b0/3.24bd,0.1505/-2.22b0/3.24bd";
			geo3.aUstr="0.1930e3ee86734b/-0.0053986904f98328,0.1613bc96ad4bf2/-0.0053986904f98328,0.1613bc96ad4bf2/0.23718be6f994c4,0.1930e3ee86734b/0.23718be6f994c4,0.17edc635ce3706/0,0.168138b954c90b/0,0.168138b954c90b/1,0.17edc635ce3706/1,0.1cbb4f9f1e6442/0.000188c9bcd1004dd,0.1cbb4f9f1e6442/1.0003a3414c77c,0.193cc01d394de3/1.0003a3414c77c,0.193cc01d394de3/0.000188c9bcd1004dd,0/0,1/0,1/1,0/1,0.17ef1c6fb98f87/0,0.1654ede09eb3a7/0,0.1654ede09eb3a7/1,0.17ef1c6fb98f87/1,0.1e5fab98b08fb7/0,0.1cc2e30adaf6e3/0,0.1cc2e30adaf6e3/1,0.1e5fab98b08fb7/1";
			geo3.aV= read(geo3.aVstr).split(",");
			geo3.aU= read(geo3.aUstr).split(",");
			geo3.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo3);
			var geo4:Object = {};
			geo4.aVstr="1b.112d/-2.232f/3c.1e32,3.71b/-2.232f/3c.1e32,2.6a0/-2.232f/3e.acc,1c.11a7/-2.232f/3e.acc,0.10e6/-2.22ae/39.1467,-1.10ea/-2.22cf/39.13fd,1f.2348/-2.232f/3a.002d,1d.24b5/-2.232f/39.22f1,1d.24b5/1.21f5/39.265c,1b.112d/1.21f5/3c.1e32,1f.2348/1.21f5/3a.0ea,1c.11a7/1.21f5/3e.acc,-1.6fd/1.1fc1/3a.0149,2.6a0/1.21f5/3e.acc,0.1bf0/1.20fd/39.2401,3.71b/1.21f5/3c.1e32";
			geo4.aUstr="0/0,1/0,1/1,0/1,0.287c17a75106f/0.22370681024fd0,0.1966d2cdd64c18/0.1de38aee8b2d44,0.1cbb2f023dd7ac/0.2ffae4b94aee7,0.1ca1e8a104167e/0.22504cbeb51e8e,0.1604b180a18dff/0,0.18fa9a4c774100/0,0.18fa9a4c774100/1,0.1604b180a18dff/1,0.16260218d2877b/0,0.193c6536f301f5/0,0.193c6536f301f5/1,0.16260218d2877b/1,0.2314613b163b1/0,0.19031fe30e5f63/0,0.19031fe30e5f63/1,0.2314613b163b1/1,0.1642a602835eb1/0,0.182f365d8a9e7c/0,0.182f365d8a9e7c/1,0.1642a602835eb1/1,0.19319e2bf15921/0.2242acfab4ab78,0.192c4c349f50f0/0.1e0cb71c952c61,0.1c9ccc17a4a85e/0.1e0ca93bde78ba,0.1ca21e327da2ff/0.22429ef6770560,0.197f867ee10dda/0.1dbdd11a0a51aa,0.199a108163410a/0.3706b549050846,0.1cd5bb60b62448/0.3683609c0b2650,0.1cbb315e33f118/0.1db0acb5a9c4a8,0.1609608b17c9b0/0,0.191fc170c91d2e/0,0.191fc170c91d2e/1,0.1609608b17c9b0/1,0.1cc9c0f118d686/0,0.1e509045f804b1/0,0.1e509045f804b1/1,0.1cc9c0f118d686/1,0.1ce4baaaf36320/-0.00a6c751b204d3d,0.3069b1254e089/0,0.3069b1254e089/0.2353967b4997e4,0.1ce4baaaf36320/0.236c433bf8ffd2,0.1e26127267ed7a/0.008823d670711320,0.1e2fa618cdf15f/0.2343820d5b2748,0.1d4c77575fa59b/0.210add54e58ac6,0.2ec4a9244b8a6/0.0c2003bb4ec3c9";
			geo4.aV= read(geo4.aVstr).split(",");
			geo4.aU= read(geo4.aUstr).split(",");
			geo4.f="0,1,2,0,1,2,0,2,3,0,2,3,2,1,4,0,1,2,2,4,5,0,2,3,0,3,6,0,1,2,0,6,7,0,2,3,0,7,8,4,5,6,0,8,9,4,6,7,7,6,a,8,9,a,7,a,8,8,a,b,6,3,b,c,d,e,6,b,a,c,e,f,2,5,c,10,11,12,2,c,d,10,12,13,5,4,e,14,15,16,5,e,c,14,16,17,4,1,f,18,19,1a,4,f,e,18,1a,1b,1,0,9,1c,1d,1e,1,9,f,1c,1e,1f,3,2,d,20,21,22,3,d,b,20,22,23,8,a,b,24,25,26,8,b,9,24,26,27,c,e,f,28,29,2a,c,f,d,28,2a,2b,b,d,f,2c,2d,2e,b,f,9,2c,2e,2f";
			geos.push(geo4);
			var geo5:Object = {};
			geo5.aVstr="1d.23e1/1.2048/4.114d,1d.23e1/-2.22b0/4.114d,1f.23e1/-2.22b0/4.114d,1f.23e1/1.2048/4.114d,1d.23e1/1.2048/3a.0391,1f.23e1/1.2048/3a.0391,1f.23e1/-2.22b0/3a.0391,1d.23e1/-2.22b0/3a.0391";
			geo5.aUstr="0.1930e3ee86734b/-0.0053986904f98328,0.1613bc96ad4bf2/-0.0053986904f98328,0.1613bc96ad4bf2/0.23718be6f994c4,0.1930e3ee86734b/0.23718be6f994c4,0.17edc635ce3706/0,0.168138b954c90b/0,0.168138b954c90b/1,0.17edc635ce3706/1,0.1cbb4f9f1e6442/0.000188c9bcd1004dd,0.1cbb4f9f1e6442/1.0003a3414c77c,0.193cc01d394de3/1.0003a3414c77c,0.193cc01d394de3/0.000188c9bcd1004dd,0/0,1/0,1/1,0/1,0.17ef1c6fb98f87/0,0.1654ede09eb3a7/0,0.1654ede09eb3a7/1,0.17ef1c6fb98f87/1,0.1e5fab98b08fb7/0,0.1cc2e30adaf6e3/0,0.1cc2e30adaf6e3/1,0.1e5fab98b08fb7/1";
			geo5.aV= read(geo5.aVstr).split(",");
			geo5.aU= read(geo5.aUstr).split(",");
			geo5.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo5);
			var geo6:Object = {};
			geo6.aVstr="3.cd2/-2.232f/0.e72,1a.1e10/-2.232f/0.e72,1b.1e8a/-2.232f/-0.1df0,2.c57/-2.232f/-0.1df0,1e.26e2/-2.232f/5.f67,20.004d/-2.232f/4.a16,-1.1113/-2.232f/4.0bc,0.13b3/-2.232f/4.03c8,0.1f56/1.21f5/4.7ad,3.cd2/1.21f5/0.e72,-1.758/1.21f5/4.766,2.c57/1.21f5/-0.1df0,20.004d/1.21f5/4.a16,1b.1e8a/1.21f5/-0.1df0,1e.26e2/1.21f5/5.f67,1a.1e10/1.21f5/0.e72";
			geo6.aUstr="0/0,1/0,1/1,0/1,0.287c17a75106f/0.22370681024fd0,0.1966d2cdd64c18/0.1de38aee8b2d44,0.1cbb2f023dd7ac/0.2ffae4b94aee7,0.1ca1e8a104167e/0.22504cbeb51e8e,0.18384ea450bc4b/0,0.163062b8cd4a24/0,0.163062b8cd4a24/1,0.18384ea450bc4b/1,0.16260218d2877b/0,0.193c6536f301f5/0,0.193c6536f301f5/1,0.16260218d2877b/1,0.2314613b163b1/0,0.19031fe30e5f63/0,0.19031fe30e5f63/1,0.2314613b163b1/1,0.1919ed05f4e2a4/0,0.16487a6d57993b/0,0.16487a6d57993b/1,0.1919ed05f4e2a4/1,0.19319e2bf15921/0.2242acfab4ab78,0.192c4c349f50f0/0.1e0cb71c952c61,0.1c9ccc17a4a85e/0.1e0ca93bde78ba,0.1ca21e327da2ff/0.22429ef6770560,0.197f867ee10dda/0.1dbdd11a0a51aa,0.199a108163410a/0.3706b549050846,0.1cd5bb60b62448/0.3683609c0b2650,0.1cbb315e33f118/0.1db0acb5a9c4a8,0.1609608b17c9b0/0,0.191fc170c91d2e/0,0.191fc170c91d2e/1,0.1609608b17c9b0/1,0.1cc9c0f118d686/0,0.1e509045f804b1/0,0.1e509045f804b1/1,0.1cc9c0f118d686/1,0.1ce4baaaf36320/-0.00a6c751b204d3d,0.3069b1254e089/0,0.3069b1254e089/0.2353967b4997e4,0.1ce4baaaf36320/0.236c433bf8ffd2,0.1e26127267ed7a/0.008823d670711320,0.1e2fa618cdf15f/0.2343820d5b2748,0.1d4c77575fa59b/0.210add54e58ac6,0.2ec4a9244b8a6/0.0c2003bb4ec3c9";
			geo6.aV= read(geo6.aVstr).split(",");
			geo6.aU= read(geo6.aUstr).split(",");
			geo6.f="0,1,2,0,1,2,0,2,3,0,2,3,2,1,4,0,1,2,2,4,5,0,2,3,0,3,6,0,1,2,0,6,7,0,2,3,0,7,8,4,5,6,0,8,9,4,6,7,7,6,a,8,9,a,7,a,8,8,a,b,6,3,b,c,d,e,6,b,a,c,e,f,2,5,c,10,11,12,2,c,d,10,12,13,5,4,e,14,15,16,5,e,c,14,16,17,4,1,f,18,19,1a,4,f,e,18,1a,1b,1,0,9,1c,1d,1e,1,9,f,1c,1e,1f,3,2,d,20,21,22,3,d,b,20,22,23,8,a,b,24,25,26,8,b,9,24,26,27,c,e,f,28,29,2a,c,f,d,28,2a,2b,b,d,f,2c,2d,2e,b,f,9,2c,2e,2f";
			geos.push(geo6);
			var geo7:Object = {};
			geo7.aVstr="1e.9e2/-0.1043/3b.0338,1e.9e2/-3.022f/3b.0338,1f.f3c/-3.022f/3b.26a9,1e.1d83/-0.1043/3b.12e3,1c.2352/-0.1043/3c.1e2f,1d.fe3/-0.1043/3d.6ca,1e.019c/-3.022f/3d.1a90,1c.2352/-3.022f/3c.1e2f";
			geo7.aUstr="0.1e38e3b460ce9c/0.13641ce63c3bed,0.1ccb5ac0bb619f/0.13641ce63c3bed,0.1ccb5ac0bb619f/0.10e95970e6decc,0.1e38e3b460ce9c/0.10e95970e6decc,0.1e6656496afc44/0.136295d2c389c3,0.1d4be95f1cd907/0.136295d2c389c3,0.1d4be95f1cd907/0.112db9a23129dc,0.1e6656496afc44/0.112db9a23129dc,0.16a2102a55036f/0,0.194b9c9226d929/0,0.194b9c9226d929/1,0.16a2102a55036f/1,0.1e536b5aece860/0.fa947a6b0dfe0,0.1e536b5aece860/0.1453803d26a25c,0.1cd7fcd520aeb8/0.1453803d26a25c,0.1cd7fcd520aeb8/0.fa947a6b0dfe0,0.1ce7d6f9a95ffc/0.153cf344487483,0.1e2a7952c1b62c/0.153cf344487483,0.1e2a7952c1b62c/0.17c49c40335ee5,0.1ce7d6f9a95ffc/0.17c49c40335ee5";
			geo7.aV= read(geo7.aVstr).split(",");
			geo7.aU= read(geo7.aUstr).split(",");
			geo7.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,1,7,6,8,9,a,1,6,2,8,a,b,2,6,5,c,d,e,2,5,3,c,e,f,4,0,3,10,11,12,4,3,5,10,12,13";
			geos.push(geo7);
			var geo8:Object = {};
			geo8.aVstr="-0.0135/-3.017a/0.1947,-0.0135/-3.017a/3c.1947,1d.25db/-3.017a/3c.1947,1d.25db/-3.017a/0.1947,-0.0135/-1.15c0/0.1947,1d.25db/-1.15c0/0.1947,1d.25db/-1.15c0/3c.1947,-0.0134/-1.15c0/3c.1947";
			geo8.aUstr="0.0a307cdb7f2dd90/0.0053986904f98328,0.1eb157df1e40a2/0,0.1eb157df1e40a2/1,0.011e8ac00090a8b/1.001566654078cd,0.00c8e2778c04c0a/0.0053986904f98328,0.15ff000ea3f977/0.00014e3d42c7f4081,0.15ff000ea3f977/1.00088eb12ba4a,0.00c8e2778c04c0a/1,0.16838a6a6c208f/0.0053986904f98328,0.18cc7231ee6059/0,0.18cc7231ee6059/1,0.240d6bc9ba2cf/1,0.17a03d5d8a0ea4/0.02cee612ee7ab1e,0.18fd572081b185/0.031a28ceadfdc24,0.191d7454170613/0.3698d785065110,0.17b23ad919c99d/0.36208408ece4d8,0.173cde4526219b/-0.0001491f964507eee,0.18f047b0ba246e/-0.0012c6adf16d26ed,0.18f047b0ba246e/0.2356e14796d4fc,0.177a8840f565e2/0.236c47d05e403a,0.1666ac5adc7c6f/0,0.17a418a197242d/0,0.17a418a197242d/1,0.1666ac5adc7c6f/1";
			geo8.aV= read(geo8.aVstr).split(",");
			geo8.aU= read(geo8.aUstr).split(",");
			geo8.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo8);
		}
		private function buildMaterials():void
		{			materialLibrary = new MaterialLibrary();
			var mData_0:MaterialData = materialLibrary.addMaterial("Materialice_");
			mData_0.materialType = "textureMaterial";
			mData_0.ambientColor = 13421772;
			mData_0.diffuseColor = 13421772;
			mData_0.shininess = NaN;
			mData_0.specularColor = 16777215;
			mData_0.textureFileName = "ice_fon_plus";
			var mElements_0:Array = mData_0.elements;
			mElements_0.push(geos[8].geometry.faces[2]);
			mElements_0.push(geos[8].geometry.faces[3]);
			mElements_0.push(geos[8].geometry.faces[4]);
			mElements_0.push(geos[8].geometry.faces[5]);
			mElements_0.push(geos[8].geometry.faces[6]);
			mElements_0.push(geos[8].geometry.faces[7]);
			mElements_0.push(geos[8].geometry.faces[8]);
			mElements_0.push(geos[8].geometry.faces[9]);
			mElements_0.push(geos[8].geometry.faces[10]);
			mElements_0.push(geos[8].geometry.faces[11]);
			
			var mData_1:MaterialData = materialLibrary.addMaterial("Noneice_.000");
			mData_1.materialType = "shadingMaterial";
			mData_1.ambientColor = 0;
			mData_1.diffuseColor = 13421772;
			mData_1.shininess = NaN;
			mData_1.specularColor = 16777215;
			mData_1.textureFileName = "null";
			var mElements_1:Array = mData_1.elements;
			mElements_1.push(geos[0].geometry.faces[0]);
			mElements_1.push(geos[0].geometry.faces[1]);
			mElements_1.push(geos[0].geometry.faces[2]);
			mElements_1.push(geos[0].geometry.faces[3]);
			mElements_1.push(geos[1].geometry.faces[0]);
			mElements_1.push(geos[1].geometry.faces[1]);
			mElements_1.push(geos[1].geometry.faces[2]);
			mElements_1.push(geos[1].geometry.faces[3]);
			mElements_1.push(geos[2].geometry.faces[0]);
			mElements_1.push(geos[2].geometry.faces[1]);
			mElements_1.push(geos[2].geometry.faces[2]);
			mElements_1.push(geos[2].geometry.faces[3]);
			mElements_1.push(geos[7].geometry.faces[6]);
			mElements_1.push(geos[7].geometry.faces[7]);
			mElements_1.push(geos[7].geometry.faces[8]);
			mElements_1.push(geos[7].geometry.faces[9]);
			
			var mData_2:MaterialData = materialLibrary.addMaterial("None");
			mData_2.materialType = "shadingMaterial";
			mData_2.ambientColor = 0;
			mData_2.diffuseColor = 13421772;
			mData_2.shininess = NaN;
			mData_2.specularColor = 16777215;
			mData_2.textureFileName = "null";
			var mElements_2:Array = mData_2.elements;
			mElements_2.push(geos[1].geometry.faces[4]);
			mElements_2.push(geos[1].geometry.faces[5]);
			mElements_2.push(geos[3].geometry.faces[6]);
			mElements_2.push(geos[3].geometry.faces[7]);
			mElements_2.push(geos[4].geometry.faces[0]);
			mElements_2.push(geos[4].geometry.faces[1]);
			mElements_2.push(geos[4].geometry.faces[2]);
			mElements_2.push(geos[4].geometry.faces[3]);
			mElements_2.push(geos[4].geometry.faces[4]);
			mElements_2.push(geos[4].geometry.faces[5]);
			mElements_2.push(geos[5].geometry.faces[6]);
			mElements_2.push(geos[5].geometry.faces[7]);
			mElements_2.push(geos[6].geometry.faces[0]);
			mElements_2.push(geos[6].geometry.faces[1]);
			mElements_2.push(geos[6].geometry.faces[2]);
			mElements_2.push(geos[6].geometry.faces[3]);
			mElements_2.push(geos[6].geometry.faces[4]);
			mElements_2.push(geos[6].geometry.faces[5]);
			
			var mData_3:MaterialData = materialLibrary.addMaterial("Noneice_.001");
			mData_3.materialType = "shadingMaterial";
			mData_3.ambientColor = 0;
			mData_3.diffuseColor = 13421772;
			mData_3.shininess = NaN;
			mData_3.specularColor = 16777215;
			mData_3.textureFileName = "null";
			var mElements_3:Array = mData_3.elements;
			mElements_3.push(geos[0].geometry.faces[4]);
			mElements_3.push(geos[0].geometry.faces[5]);
			mElements_3.push(geos[0].geometry.faces[6]);
			mElements_3.push(geos[0].geometry.faces[7]);
			mElements_3.push(geos[0].geometry.faces[8]);
			mElements_3.push(geos[0].geometry.faces[9]);
			mElements_3.push(geos[1].geometry.faces[6]);
			mElements_3.push(geos[1].geometry.faces[7]);
			mElements_3.push(geos[1].geometry.faces[8]);
			mElements_3.push(geos[1].geometry.faces[9]);
			mElements_3.push(geos[2].geometry.faces[6]);
			mElements_3.push(geos[2].geometry.faces[7]);
			mElements_3.push(geos[2].geometry.faces[8]);
			mElements_3.push(geos[2].geometry.faces[9]);
			mElements_3.push(geos[3].geometry.faces[0]);
			mElements_3.push(geos[3].geometry.faces[1]);
			mElements_3.push(geos[3].geometry.faces[2]);
			mElements_3.push(geos[3].geometry.faces[3]);
			mElements_3.push(geos[3].geometry.faces[4]);
			mElements_3.push(geos[3].geometry.faces[5]);
			mElements_3.push(geos[3].geometry.faces[8]);
			mElements_3.push(geos[3].geometry.faces[9]);
			mElements_3.push(geos[3].geometry.faces[10]);
			mElements_3.push(geos[3].geometry.faces[11]);
			mElements_3.push(geos[4].geometry.faces[6]);
			mElements_3.push(geos[4].geometry.faces[7]);
			mElements_3.push(geos[4].geometry.faces[8]);
			mElements_3.push(geos[4].geometry.faces[9]);
			mElements_3.push(geos[4].geometry.faces[10]);
			mElements_3.push(geos[4].geometry.faces[11]);
			mElements_3.push(geos[4].geometry.faces[12]);
			mElements_3.push(geos[4].geometry.faces[13]);
			mElements_3.push(geos[4].geometry.faces[14]);
			mElements_3.push(geos[4].geometry.faces[15]);
			mElements_3.push(geos[4].geometry.faces[16]);
			mElements_3.push(geos[4].geometry.faces[17]);
			mElements_3.push(geos[4].geometry.faces[18]);
			mElements_3.push(geos[4].geometry.faces[19]);
			mElements_3.push(geos[4].geometry.faces[20]);
			mElements_3.push(geos[4].geometry.faces[21]);
			mElements_3.push(geos[4].geometry.faces[22]);
			mElements_3.push(geos[4].geometry.faces[23]);
			mElements_3.push(geos[4].geometry.faces[24]);
			mElements_3.push(geos[4].geometry.faces[25]);
			mElements_3.push(geos[4].geometry.faces[26]);
			mElements_3.push(geos[4].geometry.faces[27]);
			mElements_3.push(geos[5].geometry.faces[0]);
			mElements_3.push(geos[5].geometry.faces[1]);
			mElements_3.push(geos[5].geometry.faces[2]);
			mElements_3.push(geos[5].geometry.faces[3]);
			mElements_3.push(geos[5].geometry.faces[4]);
			mElements_3.push(geos[5].geometry.faces[5]);
			mElements_3.push(geos[5].geometry.faces[8]);
			mElements_3.push(geos[5].geometry.faces[9]);
			mElements_3.push(geos[5].geometry.faces[10]);
			mElements_3.push(geos[5].geometry.faces[11]);
			mElements_3.push(geos[6].geometry.faces[6]);
			mElements_3.push(geos[6].geometry.faces[7]);
			mElements_3.push(geos[6].geometry.faces[8]);
			mElements_3.push(geos[6].geometry.faces[9]);
			mElements_3.push(geos[6].geometry.faces[10]);
			mElements_3.push(geos[6].geometry.faces[11]);
			mElements_3.push(geos[6].geometry.faces[12]);
			mElements_3.push(geos[6].geometry.faces[13]);
			mElements_3.push(geos[6].geometry.faces[14]);
			mElements_3.push(geos[6].geometry.faces[15]);
			mElements_3.push(geos[6].geometry.faces[16]);
			mElements_3.push(geos[6].geometry.faces[17]);
			mElements_3.push(geos[6].geometry.faces[18]);
			mElements_3.push(geos[6].geometry.faces[19]);
			mElements_3.push(geos[6].geometry.faces[20]);
			mElements_3.push(geos[6].geometry.faces[21]);
			mElements_3.push(geos[6].geometry.faces[22]);
			mElements_3.push(geos[6].geometry.faces[23]);
			mElements_3.push(geos[6].geometry.faces[24]);
			mElements_3.push(geos[6].geometry.faces[25]);
			mElements_3.push(geos[6].geometry.faces[26]);
			mElements_3.push(geos[6].geometry.faces[27]);
			mElements_3.push(geos[7].geometry.faces[0]);
			mElements_3.push(geos[7].geometry.faces[1]);
			mElements_3.push(geos[7].geometry.faces[2]);
			mElements_3.push(geos[7].geometry.faces[3]);
			mElements_3.push(geos[7].geometry.faces[4]);
			mElements_3.push(geos[7].geometry.faces[5]);
			
			var mData_4:MaterialData = materialLibrary.addMaterial("Noneice_fon_");
			mData_4.materialType = "shadingMaterial";
			mData_4.ambientColor = 0;
			mData_4.diffuseColor = 13421772;
			mData_4.shininess = NaN;
			mData_4.specularColor = 16777215;
			mData_4.textureFileName = "null";
			var mElements_4:Array = mData_4.elements;
			mElements_4.push(geos[2].geometry.faces[4]);
			mElements_4.push(geos[2].geometry.faces[5]);
			
			var mData_5:MaterialData = materialLibrary.addMaterial("Material");
			mData_5.materialType = "shadingMaterial";
			mData_5.ambientColor = 13421772;
			mData_5.diffuseColor = 13421772;
			mData_5.shininess = NaN;
			mData_5.specularColor = 16777215;
			mData_5.textureFileName = "null";
			var mElements_5:Array = mData_5.elements;
			mElements_5.push(geos[8].geometry.faces[0]);
			mElements_5.push(geos[8].geometry.faces[1]);
			

		}
		private function cleanUp():void
		{
			for(var i:int = 0;i<9;++i){
				objs["obj"+i] == null;
			}
			aV = null;
			aU = null;
		}

		private function addContainers():void
		{
			aC = [];
						aC.push(this);
			var m0:MatrixAway3D = new MatrixAway3D();
			m0.sxx = 2;
			m0.sxy = 0;
			m0.sxz = 0;
			m0.tx = 0*_scale;
			m0.syx = 0;
			m0.syy = 2;
			m0.syz = 0;
			m0.ty = 0*_scale;
			m0.szx = 0;
			m0.szy = 0;
			m0.szz = 2;
			m0.tz = 0*_scale;
			transform = m0;

		}

		public function get containers():Array
		{
			return aC;
		}


		public function get meshes():Array
		{
			return oList;
		}


		private function read(str:String):String
		{
			var start:int= 0;
			var chunk:String;
			var end:int= 0;
			var dec:String = "";
			var charcount:int = str.length;
			for(var i:int = 0;i<charcount;++i){
				if (str.charCodeAt(i)>=44 && str.charCodeAt(i)<= 48 ){
					dec+= str.substring(i, i+1);
				}else{
					start = i;
					chunk = "";
					while(str.charCodeAt(i)!=44 && str.charCodeAt(i)!= 45 && str.charCodeAt(i)!= 46 && str.charCodeAt(i)!= 47 && i<=charcount){
						i++;
					}
					chunk = ""+parseInt("0x"+str.substring(start, i), 16 );
					dec+= chunk;
					i--;
				}
			}
			return dec;
		}

	}
}