//AS3 exporter version 2.2, generated by Away3D: http://www.away3d.com
package katok
{
	import away3d.containers.ObjectContainer3D;
	import away3d.containers.Scene3D;
	import away3d.core.math.*;
	import away3d.materials.*;
	import away3d.core.base.*;
	import away3d.core.utils.Init;
	import away3d.loaders.utils.*;
	import away3d.loaders.data.*;
	import flash.utils.Dictionary;
	import away3d.primitives.*;

	public class KatokMesh extends ObjectContainer3D
	{
		private var objs:Object = {};
		private var geos:Array = [];
		private var oList:Array =[];
		private var aC:Array;
		private var aV:Array;
		private var aU:Array;
		private var _scale:Number;

		public function KatokMesh(init:Object = null)
		{
			var ini:Init = Init.parse(init);
			_scale = ini.getNumber("scaling", 1);
			setSource();
			addContainers();
			buildMeshes();
			//buildMaterials();
			//cleanUp();
		}

		private function buildMeshes():void
		{
			var m0:MatrixAway3D = new MatrixAway3D();
			m0.sxx = 1;
			m0.sxy = 0;
			m0.sxz = 0;
			m0.tx = 0.9600719809532166*_scale;
			m0.syx = 0;
			m0.syy = 1;
			m0.syz = 0;
			m0.ty = -0.5157217979431152*_scale;
			m0.szx = 0;
			m0.szy = 0;
			m0.szz = 1;
			m0.tz = 1.6472626030445099*_scale;

			objs.obj0 = {name:"bort_t_r",  transform:m0, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj0.geo=geos[0];
			var m1:MatrixAway3D = new MatrixAway3D();
			m1.sxx = 1;
			m1.sxy = 0;
			m1.sxz = 0;
			m1.tx = 29.34403133392334*_scale;
			m1.syx = 0;
			m1.syy = 1;
			m1.syz = 0;
			m1.ty = -0.5157216787338257*_scale;
			m1.szx = 0;
			m1.szy = 0;
			m1.szz = 1;
			m1.tz = 1.8446548283100128*_scale;

			objs.obj1 = {name:"bort_t_l",  transform:m1, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj1.geo=geos[1];
			var m2:MatrixAway3D = new MatrixAway3D();
			m2.sxx = 1;
			m2.sxy = 0;
			m2.sxz = 0;
			m2.tx = 0.8562549948692322*_scale;
			m2.syx = 0;
			m2.syy = 1;
			m2.syz = 0;
			m2.ty = -0.5303243398666382*_scale;
			m2.szx = 0;
			m2.szy = 0;
			m2.szz = 1;
			m2.tz = 60.03466606140137*_scale;

			objs.obj2 = {name:"bort_b_r",  transform:m2, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj2.geo=geos[2];
			var m3:MatrixAway3D = new MatrixAway3D();
			m3.sxx = 1;
			m3.sxy = 0;
			m3.sxz = 0;
			m3.tx = 29.671438217163086*_scale;
			m3.syx = 0;
			m3.syy = 1;
			m3.syz = 0;
			m3.ty = -0.5157206654548645*_scale;
			m3.szx = 0;
			m3.szy = 0;
			m3.szz = 1;
			m3.tz = 60.14045524597168*_scale;

			objs.obj3 = {name:"bort_b_l",  transform:m3, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj3.geo=geos[3];
			var m4:MatrixAway3D = new MatrixAway3D();
			m4.sxx = 1;
			m4.sxy = 0;
			m4.sxz = 0;
			m4.tx = -0.0378568172454834*_scale;
			m4.syx = 0;
			m4.syy = 1;
			m4.syz = 0;
			m4.ty = -1.7310083508491516*_scale;
			m4.szx = 0;
			m4.szy = 0;
			m4.szz = 1;
			m4.tz = 60.56991767883301*_scale;

			objs.obj4 = {name:"St_b_left",  transform:m4, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj4.geo=geos[4];
			var m5:MatrixAway3D = new MatrixAway3D();
			m5.sxx = 1;
			m5.sxy = 0;
			m5.sxz = 0;
			m5.tx = 29.90640926361084*_scale;
			m5.syx = 0;
			m5.syy = 1;
			m5.syz = 0;
			m5.ty = -1.7368143051862717*_scale;
			m5.szx = 0;
			m5.szy = 0;
			m5.szz = 1;
			m5.tz = 0.5505827963352203*_scale;

			objs.obj5 = {name:"St_t_right",  transform:m5, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj5.geo=geos[5];
			var m6:MatrixAway3D = new MatrixAway3D();
			m6.sxx = 1;
			m6.sxy = 0;
			m6.sxz = 0;
			m6.tx = 0.19838333129882813*_scale;
			m6.syx = 0;
			m6.syy = 1;
			m6.syz = 0;
			m6.ty = -1.7473875284194946*_scale;
			m6.szx = 0;
			m6.szy = 0;
			m6.szz = 1;
			m6.tz = 1.0158399939537048*_scale;

			objs.obj6 = {name:"St_t_left",  transform:m6, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj6.geo=geos[6];
			var m7:MatrixAway3D = new MatrixAway3D();
			m7.sxx = 1;
			m7.sxy = 0;
			m7.sxz = 0;
			m7.tx = -0.3426567614078522*_scale;
			m7.syx = 0;
			m7.syy = 1;
			m7.syz = 0;
			m7.ty = -0.5200989246368408*_scale;
			m7.szx = 0;
			m7.szy = 0;
			m7.szz = 1;
			m7.tz = 30.98613154888153*_scale;

			objs.obj7 = {name:"bort_right",  transform:m7, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj7.geo=geos[7];
			var m8:MatrixAway3D = new MatrixAway3D();
			m8.sxx = 1;
			m8.sxy = 0;
			m8.sxz = 0;
			m8.tx = 15.310766458511353*_scale;
			m8.syx = 0;
			m8.syy = 1;
			m8.syz = 0;
			m8.ty = -0.5157212018966675*_scale;
			m8.szx = 0;
			m8.szy = 0;
			m8.szz = 1;
			m8.tz = 61.52469253540039*_scale;

			objs.obj8 = {name:"bort_bottom",  transform:m8, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj8.geo=geos[8];
			var m9:MatrixAway3D = new MatrixAway3D();
			m9.sxx = 1;
			m9.sxy = 0;
			m9.sxz = 0;
			m9.tx = 30.918472290039063*_scale;
			m9.syx = 0;
			m9.syy = 1;
			m9.syz = 0;
			m9.ty = -0.5308123826980591*_scale;
			m9.szx = 0;
			m9.szy = 0;
			m9.szz = 1;
			m9.tz = 31.26710867881775*_scale;

			objs.obj9 = {name:"bort_left",  transform:m9, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj9.geo=geos[9];
			var m10:MatrixAway3D = new MatrixAway3D();
			m10.sxx = 1;
			m10.sxy = 0;
			m10.sxz = 0;
			m10.tx = 15.048884391784668*_scale;
			m10.syx = 0;
			m10.syy = 1;
			m10.syz = 0;
			m10.ty = -0.5157212018966675*_scale;
			m10.szx = 0;
			m10.szy = 0;
			m10.szz = 1;
			m10.tz = -0.19828630983829498*_scale;

			objs.obj10 = {name:"bort_top",  transform:m10, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj10.geo=geos[10];
			var m11:MatrixAway3D = new MatrixAway3D();
			m11.sxx = 1;
			m11.sxy = 0;
			m11.sxz = 0;
			m11.tx = 30.147090911865234*_scale;
			m11.syx = 0;
			m11.syy = 1;
			m11.syz = 0;
			m11.ty = -1.7361227869987488*_scale;
			m11.szx = 0;
			m11.szy = 0;
			m11.szz = 1;
			m11.tz = 60.38124084472656*_scale;

			objs.obj11 = {name:"St_b_right",  transform:m11, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj11.geo=geos[11];
			var m12:MatrixAway3D = new MatrixAway3D();
			m12.sxx = 1;
			m12.sxy = 0;
			m12.sxz = 0;
			m12.tx = 14.969133843667805*_scale;
			m12.syx = 0;
			m12.syy = 1;
			m12.syz = 0;
			m12.ty = -2.2972689270973206*_scale;
			m12.szx = 0;
			m12.szy = 0;
			m12.szz = 1;
			m12.tz = 30.64709883928299*_scale;

			objs.obj12 = {name:"Ice",  transform:m12, pivotPoint:new Number3D(0,0,0), container:0, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj12.geo=geos[12];

			var ref:Object;
			var mesh:Mesh;
			var j:int;
			var av:Array;
			var au:Array;
			var v0:Vertex;
			var v1:Vertex;
			var v2:Vertex;
			var u0:UV;
			var u1:UV;
			var u2:UV;
			var aRef:Array ;
			for(var i:int = 0;i<13;++i){
				ref = objs["obj"+i];
				if(ref != null){
					mesh = new Mesh();
					mesh.type = ".as";
					mesh.bothsides = ref.bothsides;
					mesh.name = ref.name;
					mesh.pushfront = ref.pushfront;
					mesh.pushback = ref.pushback;
					mesh.ownCanvas = ref.ownCanvas;
					if(aC[ref.container]!= null)
						aC[ref.container].addChild(mesh);

					oList.push(mesh);
					mesh.transform = ref.transform;
					mesh.movePivot(ref.pivotPoint.x, ref.pivotPoint.y, ref.pivotPoint.z);
					if (ref.geo.geometry != null) {
						mesh.geometry = ref.geo.geometry;
						continue;
					}
					ref.geo.geometry = new Geometry();
					mesh.geometry = ref.geo.geometry;
					aRef = ref.geo.f.split(",");
					for(j = 0;j<aRef.length;j+=6){
						try{
							av = ref.geo.aV[parseInt(aRef[j], 16)].split("/");
							v0 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							av = ref.geo.aV[parseInt(aRef[j+1],16)].split("/");
							v1 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							av = ref.geo.aV[parseInt(aRef[j+2],16)].split("/");
							v2 = new Vertex(Number(parseFloat(av[0]))*_scale, Number(parseFloat(av[1]))*_scale, Number(parseFloat(av[2]))*_scale);
							au = ref.geo.aU[parseInt(aRef[j+3],16)].split("/");
							u0 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							au = ref.geo.aU[parseInt(aRef[j+4],16)].split("/");
							u1 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							au = ref.geo.aU[parseInt(aRef[j+5],16)].split("/");
							u2 = new UV(parseFloat(au[0]), parseFloat(au[1]));
							ref.geo.geometry.addFace( new Face(v0, v1, v2, ref.material, u0, u1, u2) );
						}catch(e:Error){
							trace("obj"+i+": ["+aV[parseInt(aRef[j],16)].split("/")+"],["+aV[parseInt(aRef[j+1],16)].split("/")+"],["+aV[parseInt(aRef[j+2],16)].split("/")+"]");
							trace("     uvs: ["+aV[parseInt(aRef[j+3],16)].split("/")+"],["+aV[parseInt(aRef[j+4],16)].split("/")+"],["+aU[parseInt(aRef[j+5],16)].split("/")+"]");
						}
					}
				}
			}
		} 

		private function setSource():void
		{
			var geo0:Object = {};
			geo0.aVstr="1.de7/2.f0a/-2.1028,-2.5c8/2.f0a/2.fa1,-2.f84/-2.f0a/2.e84,1.de7/-2.f0a/-2.1028,2.f84/2.f0a/-1.ad7,-0.69a/2.f0a/2.ef9,-2.5c8/2.f0a/2.1028,2.f84/-1.400/-1.ad7,-0.b0f/-0.26d1/2.d53,-2.f84/-2.f0a/2.c95";
			geo0.aUstr="0.193c6536f301f5/1,0.16260218d2877b/1,0.16260218d2877b/0,0.193c6536f301f5/0,0.1e509045f804b1/1,0.1cc9c0f118d686/1,0.1cc9c0f118d686/0,0.1e509045f804b1/0,0.287c17a75106f/0.22370681024fd0,0.1966d2cdd64c18/0.1de38aee8b2d44,0.1cbb2f023dd7ac/0.2ffae4b94aee7,0.1ca1e8a104167e/0.22504cbeb51e8e,0/0,1/0,1/1,0/1,0.1957f3fcf2a766/0,0.1c892ba3a7e17c/0,0.1c892ba3a7e17c/0.015150849cd54c4,0.1957f3fcf2a766/0.015150849cd54c4";
			geo0.aV= read(geo0.aVstr).split(",");
			geo0.aU= read(geo0.aUstr).split(",");
			geo0.f="0,1,2,0,1,2,0,2,3,0,2,3,0,4,5,4,5,6,0,5,6,4,6,7,7,8,5,8,9,a,7,5,4,8,a,b,7,3,9,c,d,e,7,9,8,c,e,f,1,5,8,10,11,12,1,8,2,10,12,13";
			geos.push(geo0);
			var geo1:Object = {};
			geo1.aVstr="2.1691/2.816/2.15c0,-1.15f6/2.f0a/-2.17de,-1.15f6/-2.f0a/-2.17de,2.1688/-2.efc/2.1771,-2.1671/2.f0a/-1.128d,2.15db/2.a65/2.176d,0.17da/2.f0a/2.17de,0.1783/-1.02a4/2.1553,-2.1691/-1.02a4/-1.12aa,2.165e/-2.f0a/2.176d";
			geo1.aUstr="0.19031fe30e5f63/1,0.2314613b163b1/1,0.2314613b163b1/0,0.19031fe30e5f63/0,0.3069b1254e089/0.2353967b4997e4,0.1ce4baaaf36320/0.236c433bf8ffd2,0.1ce4baaaf36320/0.00a6c751b204d3d,0.3069b1254e089/0,0.1c9ccc17a4a85e/0.1e0ca93bde78ba,0.1ca21e327da2ff/0.22429ef6770560,0.19319e2bf15921/0.2242acfab4ab78,0.192c4c349f50f0/0.1e0cb71c952c61,0/0,1/0,1/1,0/1,0.19815f2c4e98b4/0,0.1d0f671fa1ad04/0,0.1d0f671fa1ad04/0.0e730179324761,0.19815f2c4e98b4/0.0e730179324761";
			geo1.aV= read(geo1.aVstr).split(",");
			geo1.aU= read(geo1.aUstr).split(",");
			geo1.f="0,1,2,0,1,2,0,2,3,0,2,3,4,1,5,4,5,6,4,5,6,4,6,7,4,6,7,8,9,a,4,7,8,8,a,b,2,8,7,c,d,e,2,7,9,c,e,f,6,5,9,10,11,12,6,9,7,10,12,13";
			geos.push(geo1);
			var geo2:Object = {};
			geo2.aVstr="2.c99/2.e53/0.1a42,1.c3e/2.f9c/2.971,-2.0160/2.d69/-2.0012,-0.582/2.ea4/-2.46a,-0.149a/-1.490/-2.971,2.c26/-1.607/0.14c4,-2.c99/-2.e18/-2.49c,1.cf5/-2.f9c/2.573";
			geo2.aUstr="0.3069b1254e089/0.2353967b4997e4,0.1ce4baaaf36320/0.236c433bf8ffd2,0.1ce4baaaf36320/0.00a6c751b204d3d,0.3069b1254e089/0,0.1c9ccc17a4a85e/0.1e0ca93bde78ba,0.1ca21e327da2ff/0.22429ef6770560,0.195ea7f9fe8733/0.224b716f16c99c,0.195955df258c93/0.1e157b90f74a85,0.1642a602835eb1/0,0.182f365d8a9e7c/0,0.182f365d8a9e7c/1,0.1642a602835eb1/1,0.2314613b163b1/0,0.19031fe30e5f63/0,0.19031fe30e5f63/0.3539afb872027c,0.2314613b163b1/0.3539afb872027c,0/0,1/0,1/1,0/1";
			geo2.aV= read(geo2.aVstr).split(",");
			geo2.aU= read(geo2.aUstr).split(",");
			geo2.f="0,1,2,0,1,2,0,2,3,0,2,3,0,3,4,4,5,6,0,4,5,4,6,7,6,4,3,8,9,a,6,3,2,8,a,b,7,6,2,c,d,e,7,2,1,c,e,f,7,5,4,10,11,12,7,4,6,10,12,13";
			geos.push(geo2);
			var geo3:Object = {};
			geo3.aVstr="-1.893/2.f0a/2.54f,-2.90e/2.f0a/0.18b6,0.884/2.f0a/-2.413,2.90e/2.f0a/-2.016d,2.90e/2.f0a/-2.01ca,2.90e/-2.f0a/-2.54f,-1.893/-2.f0a/2.54f,0.aec/-1.0fc/-2.03b4,0.719/2.f0a/-2.0355,-2.90e/-1.0fc/0.18b6";
			geo3.aUstr="0.1e509045f804b1/1,0.1cc9c0f118d686/1,0.1cc9c0f118d686/0,0.1e509045f804b1/0,0.19638c95ee4f66/0.71af8f0a9c8e00,0.164d2977cdd4ed/0.71af8f0a9c8e00,0.16260218d2877b/0,0.193c6536f301f5/0,0.1604b180a18dff/0,0.18fa9a4c774100/0,0.18f70732869e77/0.341519d48adda4,0.16011c2e41c479/0.341519d48adda4,0.1964139dd5c227/0.22370681024fd0,0.196a94655e2edf/0.1e04d92ac60d54,0.1ca4aa2cfab9db/0.1e05936830f32a,0.1ca1e8a104167e/0.22504cbeb51e8e,0/0,1/0,1/1,0/1";
			geo3.aV= read(geo3.aVstr).split(",");
			geo3.aU= read(geo3.aUstr).split(",");
			geo3.f="0,1,2,0,1,2,0,2,3,0,2,3,0,4,5,4,5,6,0,5,6,4,6,7,7,5,4,8,9,a,7,4,8,8,a,b,9,7,8,c,d,e,9,8,1,c,e,f,9,6,5,10,11,12,9,5,7,10,12,13";
			geos.push(geo3);
			var geo4:Object = {};
			geo4.aVstr="0.1d37/1.caa/0.1eae,-0.181a/1.caa/-0.22d7,-0.49f/1.caa/-1.ba1,1.9a2/1.caa/0.ed4,0.49f/-1.caa/1.ba1,-1.9a2/-1.caa/-0.ed4,1.9a2/-1.caa/0.ed4,-0.49f/-1.caa/-1.ba1";
			geo4.aUstr="0.1e5bfef5c1acdb/0.1938cb502df807,0.1cf9e255efce9c/0.1938cb502df807,0.1cf9e255efce9c/0.16828802e4c7b9,0.1e5bfef5c1acdb/0.16828802e4c7b9,0.1ce2620980b1c9/0.17265e04484431,0.1ce2620980b1c9/0.152b4506b778cd,0.1e572cf274cb27/0.152b4506b778cd,0.1e572cf274cb27/0.17265e04484431,0.163863a3730f33/0,0.1812d1752bb976/0,0.1812d1752bb976/1,0.163863a3730f33/1,0.1d006a0dd39528/0.12a1a2c07e76fb,0.1de21f9c7fe268/0.12a1a2c07e76fb,0.1de21f9c7fe268/0.13835aab20dda7,0.1d006a0dd39528/0.13835aab20dda7,0.303d25d2af90c/0.147a45e9073c7b,0.1cc61906162681/0.147a45e9073c7b,0.1cc61906162681/0.1e903adfea944,0.303d25d2af90c/0.1e903adfea944";
			geo4.aV= read(geo4.aVstr).split(",");
			geo4.aU= read(geo4.aUstr).split(",");
			geo4.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,6,7,5,8,9,a,6,5,4,8,a,b,2,1,5,c,d,e,2,5,7,c,e,f,3,6,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo4);
			var geo5:Object = {};
			geo5.aVstr="-0.1fce/1.b7e/-0.1bfd,0.1b14/1.b7e/0.2095,0.911/1.b7e/1.b07,-1.ac0/1.b7e/-0.a7b,-0.911/-1.b7e/-1.b07,1.ac0/-1.b7e/0.a7b,-1.ac0/-1.b7e/-0.a7b,0.911/-1.b7e/1.b07";
			geo5.aUstr="0.1e25925adbd48d/0.1d58b9f119665d,0.1d05ca2cea35e0/0.1d58b9f119665d,0.1d05ca2cea35e0/0.1c38ef6731ae44,0.1e25925adbd48d/0.1c38ef6731ae44,0.302cb086d01b7/0.16d570d6b89e63,0.302cb086d01b7/0.183aa7694a6012,0.1d155536fb1a50/0.183aa7694a6012,0.1d155536fb1a50/0.16d570d6b89e63,0/0,1/0,1/1,0/1,0.1e2de973dbb2b3/0.1da37ca901aafb,0.1d05a99009a949/0.1da37ca901aafb,0.1d05a99009a949/0.1c7b3cc52fa191,0.1e2de973dbb2b3/0.1c7b3cc52fa191,0.3060e32bc28ce/0.1b428fe91ef508,0.1cd17c0d984200/0.1b428fe91ef508,0.1cd17c0d984200/0.19d77dd7d6ac8d,0.3060e32bc28ce/0.19d77dd7d6ac8d";
			geo5.aV= read(geo5.aVstr).split(",");
			geo5.aU= read(geo5.aUstr).split(",");
			geo5.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,6,7,5,8,9,a,6,5,4,8,a,b,2,1,5,c,d,e,2,5,7,c,e,f,3,6,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo5);
			var geo6:Object = {};
			geo6.aVstr="-0.14c7/1.b96/0.24eb,0.1a41/1.b96/-0.2140,1.80e/1.b96/-0.1344,0.0016/1.b96/1.bd7,-1.80e/-1.b96/0.1344,-0.0016/-1.b96/-1.bd7,1.80e/-1.b96/-0.1344,0.0016/-1.b96/1.bd7";
			geo6.aUstr="0.30ab43461577b/0.0020a72a6c560d38,0.30ab43461577b/0.2384efd9217550,0.1cf289101208e4/0.38d4b6bb58e46,0.1cf28b6c082250/0.00184b1febd6b34e,0.1ce8c2342891eb/0.eefc9e2c4defe,0.1ce8c2342891eb/0.82abc27bb1f770,0.1e489b0399cc4d/0.82abc27bb1f770,0.1e489b0399cc4d/0.eefc9e2c4defe,0.1648ec80a60c11/0,0.197a24275b4626/0,0.197a24275b4626/1,0.1648ec80a60c11/1,0.1df1aaca17b948/0.f93b7467aee05,0.1d7266bd5a0db6/0.f8e265f9a6cdc,0.1ce02c3d5db404/0.89add466b77758,0.1e0020d3fe5e63/0.dd12df3c91fc4,0.1dfd37bacbd49c/0.660269d25ccba4,0.1cd04d60e8cfe9/0.660269d25ccba4,0.1cd04d60e8cfe9/0.90688ebbf4977,0.1dfd37bacbd49c/0.90688ebbf4977";
			geo6.aV= read(geo6.aVstr).split(",");
			geo6.aU= read(geo6.aUstr).split(",");
			geo6.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,3,2,6,8,9,a,3,6,7,8,a,b,2,1,5,c,d,e,2,5,6,c,e,f,3,7,4,10,11,12,3,4,0,10,12,13";
			geos.push(geo6);
			var geo7:Object = {};
			geo7.aVstr="1.4a8/2.d48/1b.01c9,0.2268/-2.e5f/1a.178c,-1.4a8/-2.e5f/1a.178c,-0.2268/2.d48/1b.01c9,1.4a8/2.e5f/-1a.2547,-0.2268/2.e3e/-1a.2547,-1.4a8/-2.e5f/-1b.01c9,0.2268/-2.e5f/-1b.01c9";
			geo7.aUstr="0.1930e3ee86734b/0.0053986904f98328,0.1613bc96ad4bf2/0.0053986904f98328,0.1613bc96ad4bf2/0.23718be6f994c4,0.1930e3ee86734b/0.23718be6f994c4,0.17edc635ce3706/0,0.168138b954c90b/0,0.168138b954c90b/1,0.17edc635ce3706/1,0.1cbb4f9f1e6442/0.000188c9bcd1004dd,0.1cbb4f9f1e6442/0.270f,0.193cc01d394de3/0.270f,0.193cc01d394de3/0.000188c9bcd1004dd,0/0,1/0,1/1,0/1,0.17ef1c6fb98f87/0,0.1654ede09eb3a7/0,0.1654ede09eb3a7/1,0.17ef1c6fb98f87/1,0.1e5fab98b08fb7/0,0.1cc2e30adaf6e3/0,0.1cc2e30adaf6e3/1,0.1e5fab98b08fb7/1";
			geo7.aV= read(geo7.aVstr).split(",");
			geo7.aU= read(geo7.aUstr).split(",");
			geo7.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo7);
			var geo8:Object = {};
			geo8.aVstr="c.509/-2.f0a/-0.1d5d,-c.509/-2.f0a/-0.1d5d,-d.584/-2.f0a/0.1d5d,d.584/-2.f0a/0.1d5d,c.509/2.f0a/-0.1d5d,-c.509/2.f0a/-0.1d5d,-d.584/2.f0a/0.1d5d,d.584/2.f0a/0.1d5d";
			geo8.aUstr="0/0,1/0,1/1,0/1,0.197f867ee10dda/0.1dbdd11a0a51aa,0.199a108163410a/0.3706b549050846,0.1cd5bb60b62448/0.3683609c0b2650,0.1cbb315e33f118/0.1db0acb5a9c4a8,0.1609608b17c9b0/0,0.191fc170c91d2e/0,0.191fc170c91d2e/1,0.1609608b17c9b0/1,0.1e26127267ed7a/0.008823d670711320,0.1e2fa618cdf15f/0.2343820d5b2748,0.1d4c77575fa59b/0.210add54e58ac6,0.2ec4a9244b8a6/0.0c2003bb4ec3c9";
			geo8.aV= read(geo8.aVstr).split(",");
			geo8.aU= read(geo8.aUstr).split(",");
			geo8.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,3,2,6,8,9,a,3,6,7,8,a,b,7,6,5,c,d,e,7,5,4,c,e,f";
			geos.push(geo8);
			var geo9:Object = {};
			geo9.aVstr="-1.0000/2.df4/-1a.2032,-1.0000/-2.df4/-1a.2032,1.0000/-2.df4/-1a.2032,0.267c/2.aec/-1a.2032,-1.0000/2.df4/1a.2032,1.0000/2.df4/1a.2032,1.0000/-2.df4/1a.2032,-1.0000/-2.df4/1a.2032";
			geo9.aUstr="0.1930e3ee86734b/0.0053986904f98328,0.1613bc96ad4bf2/0.0053986904f98328,0.1613bc96ad4bf2/0.23718be6f994c4,0.1930e3ee86734b/0.23718be6f994c4,0.17edc635ce3706/0,0.168138b954c90b/0,0.168138b954c90b/1,0.17edc635ce3706/1,0.1cbb4f9f1e6442/0.000188c9bcd1004dd,0.1cbb4f9f1e6442/0.270f,0.193cc01d394de3/0.270f,0.193cc01d394de3/0.000188c9bcd1004dd,0/0,1/0,1/1,0/1,0.17ef1c6fb98f87/0,0.1654ede09eb3a7/0,0.1654ede09eb3a7/1,0.17ef1c6fb98f87/1,0.1e5fab98b08fb7/0,0.1cc2e30adaf6e3/0,0.1cc2e30adaf6e3/1,0.1e5fab98b08fb7/1";
			geo9.aV= read(geo9.aVstr).split(",");
			geo9.aU= read(geo9.aUstr).split(",");
			geo9.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo9);
			var geo10:Object = {};
			geo10.aVstr="-b.1c27/-2.f0a/0.1631,b.1c27/-2.f0a/0.1631,c.1ca1/-2.f0a/-0.1631,-c.1ca1/-2.f0a/-0.1631,-b.1c27/2.f0a/0.1631,b.1c27/2.f0a/0.1631,c.1ca1/2.f0a/-0.1631,-c.1ca1/2.f0a/-0.1631";
			geo10.aUstr="0/0,1/0,1/1,0/1,0.197f867ee10dda/0.1dbdd11a0a51aa,0.199a108163410a/0.3706b549050846,0.1cd5bb60b62448/0.3683609c0b2650,0.1cbb315e33f118/0.1db0acb5a9c4a8,0.1609608b17c9b0/0,0.191fc170c91d2e/0,0.191fc170c91d2e/1,0.1609608b17c9b0/1,0.1e26127267ed7a/0.008823d670711320,0.1e2fa618cdf15f/0.2343820d5b2748,0.1d4c77575fa59b/0.210add54e58ac6,0.2ec4a9244b8a6/0.0c2003bb4ec3c9";
			geo10.aV= read(geo10.aVstr).split(",");
			geo10.aU= read(geo10.aUstr).split(",");
			geo10.f="0,1,2,0,1,2,0,2,3,0,2,3,1,0,4,4,5,6,1,4,5,4,6,7,3,2,6,8,9,a,3,6,7,8,a,b,7,6,5,c,d,e,7,5,4,c,e,f";
			geos.push(geo10);
			var geo11:Object = {};
			geo11.aVstr="0.423/1.c7e/-1.bac,0.423/-1.c7e/-1.bac,1.97d/-1.c7e/-0.f4b,0.17c4/1.c7e/-0.2312,-1.97d/1.c7e/0.f4b,-0.1cec/1.c7e/0.1ef5,-0.423/-1.c7e/1.bac,-1.97d/-1.c7e/0.f4b";
			geo11.aUstr="0.1e38e3b460ce9c/0.13641ce63c3bed,0.1ccb5ac0bb619f/0.13641ce63c3bed,0.1ccb5ac0bb619f/0.10e95970e6decc,0.1e38e3b460ce9c/0.10e95970e6decc,0.1e6656496afc44/0.136295d2c389c3,0.1d4be95f1cd907/0.136295d2c389c3,0.1d4be95f1cd907/0.112db9a23129dc,0.1e6656496afc44/0.112db9a23129dc,0.16a2102a55036f/0,0.194b9c9226d929/0,0.194b9c9226d929/1,0.16a2102a55036f/1,0.1e536b5aece860/0.fa947a6b0dfe0,0.1e536b5aece860/0.1453803d26a25c,0.1cd7fcd520aeb8/0.1453803d26a25c,0.1cd7fcd520aeb8/0.fa947a6b0dfe0,0.1ce7d6f9a95ffc/0.153cf344487483,0.1e2a7952c1b62c/0.153cf344487483,0.1e2a7952c1b62c/0.17c49c40335ee5,0.1ce7d6f9a95ffc/0.17c49c40335ee5";
			geo11.aV= read(geo11.aVstr).split(",");
			geo11.aU= read(geo11.aUstr).split(",");
			geo11.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,1,7,6,8,9,a,1,6,2,8,a,b,2,6,5,c,d,e,2,5,3,c,e,f,4,0,3,10,11,12,4,3,5,10,12,13";
			geos.push(geo11);
			var geo12:Object = {};
			geo12.aVstr="-f.0000/-0.1ced/-1e.0000,-f.0000/-0.1ced/1e.0000,f.0000/-0.1ced/1e.0000,f.0000/-0.1ced/-1e.0000,-f.0000/0.1ced/-1e.0000,f.0000/0.1ced/-1e.0000,f.0000/0.1ced/1e.0000,-f.0000/0.1ced/1e.0000";
			geo12.aUstr="0.0a307cdb7f2dd90/0.0053986904f98328,0.1eb157df1e40a2/0,0.1eb157df1e40a2/1,0.011e8ac00090a8b/0.270f,0.00c8e2778c04c0a/0.0053986904f98328,0.15ff000ea3f977/0.00014e3d42c7f4081,0.15ff000ea3f977/0.270f,0.00c8e2778c04c0a/1,0.16838a6a6c208f/0.0053986904f98328,0.18cc7231ee6059/0,0.18cc7231ee6059/1,0.240d6bc9ba2cf/1,0.17a03d5d8a0ea4/0.02cee612ee7ab1e,0.18fd572081b185/0.031a28ceadfdc24,0.191d7454170613/0.3698d785065110,0.17b23ad919c99d/0.36208408ece4d8,0.173cde4526219b/0.0001491f964507eee,0.18f047b0ba246e/0.0012c6adf16d26ed,0.18f047b0ba246e/0.2356e14796d4fc,0.177a8840f565e2/0.236c47d05e403a,0.1666ac5adc7c6f/0,0.17a418a197242d/0,0.17a418a197242d/1,0.1666ac5adc7c6f/1";
			geo12.aV= read(geo12.aVstr).split(",");
			geo12.aU= read(geo12.aUstr).split(",");
			geo12.f="0,1,2,0,1,2,0,2,3,0,2,3,4,5,6,4,5,6,4,6,7,4,6,7,0,4,7,8,9,a,0,7,1,8,a,b,1,7,6,c,d,e,1,6,2,c,e,f,2,6,5,10,11,12,2,5,3,10,12,13,4,0,3,14,15,16,4,3,5,14,16,17";
			geos.push(geo12);
		} 

		private function addContainers():void
		{
			aC = [];
						aC.push(this);
			var m0:MatrixAway3D = new MatrixAway3D();
			m0.sxx = 2;
			m0.sxy = 0;
			m0.sxz = 0;
			m0.tx = 0*_scale;
			m0.syx = 0;
			m0.syy = 2;
			m0.syz = 0;
			m0.ty = 0*_scale;
			m0.szx = 0;
			m0.szy = 0;
			m0.szz = 2;
			m0.tz = 0*_scale;
			transform = m0;

		}

		public function get containers():Array
		{
			return aC;
		}


		public function get meshes():Array
		{
			return oList;
		}


		private function read(str:String):String
		{
			var start:int= 0;
			var chunk:String;
			var end:int= 0;
			var dec:String = "";
			var charcount:int = str.length;
			for(var i:int = 0;i<charcount;++i){
				if (str.charCodeAt(i)>=44 && str.charCodeAt(i)<= 48 ){
					dec+= str.substring(i, i+1);
				}else{
					start = i;
					chunk = "";
					while(str.charCodeAt(i)!=44 && str.charCodeAt(i)!= 45 && str.charCodeAt(i)!= 46 && str.charCodeAt(i)!= 47 && i<=charcount){
						i++;
					}
					chunk = ""+parseInt("0x"+str.substring(start, i), 16 );
					dec+= chunk;
					i--;
				}
			}
			return dec;
		}

	}
}